// <auto-generated />
using ExercicioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExercicioApi.Migrations
{
    [DbContext(typeof(MusicaContext))]
    [Migration("20230907202431_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExercicioApi.Modelos.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.Property<string>("Artista")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "artist");

                    b.Property<int>("Duracao")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "duration_ms");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "genre");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "song");

                    b.HasKey("Id");

                    b.ToTable("Musicas");
                });
#pragma warning restore 612, 618
        }
    }
}
